# LiteFS v0.5.x config

fuse:
  dir: "/mnt/litefs"
  allow-other: true

data:
  dir: "/data/litefs"
  compress: true
  retention: "10m"
  retention-monitor-interval: "1m"

lease:
  type: "consul"
  advertise-url: "http://${LITEFS_ADVERTISE_URL}:20202"
  consul:
    url: "http://localhost:8500"
    key: "litefs/primary"
    ttl: "10s"
    lock-delay: "5s"

exec:
  - cmd: "/usr/local/bin/run-app.sh"
